version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/printscript-ui
      - /printscript-ui/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
